### ISSUE TITLE
Discord? 

### ISSUE THREAD

**Issue by Danply** [Scrut1ny/Windows-Spoofer#2]
Can you hit me up on discord?
Danply#0019
Appreciate it.

**Comment by Scrut1ny** [comment]
Done. ✅

**Comment by Scrut1ny** [comment]
Did you fucking die or something? 😂

**Comment by Danply** [comment]
> 

im certainly alive, just got busy, 
add me once more please.

**Comment by Scrut1ny** [comment]
Okay man I added you again.
